language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t urajes123/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run urajes123/react-test npm test -- --coverage
  - docker run -e CI=true urajes123/react-test npm test

after_success:
  - docker build -t urajes123/multi-client ./client
  - docker build -t urajes123/multi-nginx ./nginx
  - docker build -t urajes123/multi-server ./server
  - docker build -t urajes123/multi-worker ./worker
  #Login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push urajes123/multi-nginx
  - docker push urajes123/multi-server
  - docker push urajes123/multi-worker
  - docker push urajes123/multi-client

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-825881790929
  docker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
